version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: finstar
    ports:
      - "5432:5432"
    volumes:
      - "../data:/var/lib/postgresql/data"

  finstar:
    container_name: finstar
    env_file: ../.env
    build:
      context: ../
      dockerfile: ./build/Dockerfile
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - "./migrations:/migrations"